### PR TITLE
Use Babel's js parser

### PR DESCRIPTION
**Pull request by jmfederico**
Currently, this extractor does not takes into account the keyword arguments which instructs which functions are to be searched for.

By using the same js parser that babel uses, we can offload most of the work to babel itself, and now it searches for any keyword as function, not only gettext and ngettext.

### CODE REVIEW

**Comment by ykshatroff** [comment]
@jmfederico Thank you for the pull request! Looks fine, I approve.

**Comment by nonamenix** [comment]
@jmfederico many thanks for your PR

**Comment by nonamenix** [comment]
Version 1.3 now available in pypi: https://pypi.python.org/pypi/babel-vue-extractor

**Comment by jmfederico** [comment]
Great!

Glad I could contribute.

**Pull request merged**
